# Generated by Django 4.1.5 on 2024-12-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_transactionmaster_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=150)),
                ('edition', models.CharField(max_length=100)),
                ('no_of_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('returned_date', models.DateField()),
                ('b_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
                ('is_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bookissued')),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionmaster',
            name='committeeDesignation',
        ),
        migrations.RemoveField(
            model_name='transactionmaster',
            name='committeeName',
        ),
        migrations.RemoveField(
            model_name='transactionmaster',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='studentmaster',
            name='studentCaste',
        ),
        migrations.DeleteModel(
            name='CommitteeDepartment',
        ),
        migrations.DeleteModel(
            name='CommitteeMaster',
        ),
        migrations.DeleteModel(
            name='TransactionMaster',
        ),
        migrations.AddField(
            model_name='bookreturned',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentmaster'),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='std_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentmaster'),
        ),
    ]
