# Generated by Django 5.2 on 2026-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_book_bookissued_bookreturned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.IntegerField(unique=True),
        ),
    ]
